### ISSUE TITLE
An Error: RuntimeError: 0D or 1D target tensor expected, multi-target not supported

### ISSUE THREAD

**Issue by gredagger** [Vidhiwar/multimodal-ecg-classification#4]
Traceback (most recent call last):
  File "ecg_mitbih.py", line 431, in <module>
    main()
  File "ecg_mitbih.py", line 288, in main
    train_loss, train_acc = train(trainloader, model, criterion, optimizer, epoch, use_cuda)
  File "ecg_mitbih.py", line 337, in train
    loss = criterion(outputs, targets)
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

I recived this error when I tried to run `ecg_mitbih.py`. I try to output the shape of outputs and targets, where cause the error. I found that outputs is batch_size * 6 with targets is batch_size * 10.
(Before that, I follow the `transform_data.ipynb`, and get the dataset as ecg signal partitioned into 10 segments. Maybe the error is caused by that?)

**Comment by Vidhiwar** [comment]
Hello, I believed the error is occurring since the targets size is batch_size*10, For this project the target size should be batch_size*1 (not one-hot encoded).

Thanks.

**Comment by vanco24** [comment]
Same doubts as well. Have you solved it?
